config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  devise_for :users
  
  resources :homepage, only: [:index]
  resources :users

  resources :orderonline, only: :index
  resources :truck, only: :index
  resources :menu, only: :index
  resources :events, only: :index
  resources :thetruck, only: :index
  resources :admins, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/homepage.rb
class Homepage < ApplicationRecord
end

app/models/orderonline.rb
class OrderOnline < ApplicationRecord 

end

app/models/truck.rb
class Truck < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  validates :email, presence: true
  validates :role, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  def admin?
    role == "admin"
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }


  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
 end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index

  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index

  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index

  end 
end

app/controllers/orderonline_controller.rb
class OrderonlineController < ApplicationController

  def index

  end
end

app/controllers/thetruck_controller.rb
class ThetruckController < ApplicationController
  def index
  end 
end

app/controllers/truck_controller.rb
class TruckController < ApplicationController

  def index
    location = '22 main st Boston MA'
    json = HTTP.get('https://maps.googleapis.com/maps/api/geocode/json',
      params:{
        address: location,
        key: Rails.application.credentials.google_maps_key
    })

    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user

  def index
    @users = User.all
    binding.pry
  end

  def show

  end

  def create

  end

  def new
  end

  private

  def authorize_user
    if !current_user.admin? || !current_user
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Admin</p>
</div>


<% if user_signed_in? %>
  <ul>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete  %></li>

    <li><%= link_to "Sign In", new_user_session_path %></li>
  </ul>

  <% else %>

  <ul>
    <li><%= link_to 'Sign In', new_user_session_path %></li>
  </ul>




<% end %>

app/views/events/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Events</p>
</div>

<h1>Coming Soon!</h1>

app/views/homepage/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Benvenuto</p>
</div>

<section>
  <aside class="right">
    <%= image_tag 'truck9-16.jpg', class: 'truck-pic' %>
    <div class="bottom">
      <li class="one"><%= image_tag("pizza7.jpg")%></li>
      <li class="two"><%= image_tag("pizza6.jpg")%></li>
      <li class="three"><%= image_tag("pizza5.jpg")%></li>
    </div>
  </aside>

  <article class="left">
    <h1 class="making-pizza">Rossano's is the best pizza truck</h1>

    <h2 class="first">Ingredients</h2>
    <p class="first-p">Ingredients are everything to us. We handcraft our pizza sauces, salad
      dressings and signature dough daily using only the finest natural, unrefined
      ingredients. We allow our dough to rest at least a day, then hand toss it
      to ensure a delicious, golden crust. We also offer delicious, crispy,
      gluten-free crust. Our gourmet pizzas, salads and sandwiches are made when
      you order and topped with locally-grown and organic herbs and vegetables*,
      artisan meats and cheeses, and imported extra virgin olive oil.
    </p>
    <h2 class="seconde">Preparation</h2>
    <p class="seconde-p">
      Most Neapolitan pizza recipes call for placing tomatoes right onto the
      dough. The San Marzano variety of tomato is a type of Italian tomato that
      is most often used on Neapolitan pizza. You can find canned San Marzano
      tomatoes in many grocery stores in the United States these days.

      But recently, Alex and I discovered an even better trick for making a tomato
      sauce that was closer to what we remember from our Neapolitan pizza. Using
      fire-roasted tomatoes! They have a flavor that’s extremely sweet right out of
      the can. This Easy Pizza Sauce uses just 5 ingredients to make a flavor-popping
      pizza sauce that reminds us of the best pizza in Naples Italy.
    </p>
  </article>
</section>

app/views/index/index.html.erb
<header>
  <aside class="asideNavbar">
    <i id="navbar" class="material-icons">dehaze</i>
    <nav class="navbar">
      <!-- logo in mobel navbar -->
      <div id="logo">
        <a href="#">Rossano's</a>
      </div>

      <ul class="navbar">
        <li><a href="#">Order Online</a></li>
        <div class="border"></div>
        <li><a href="#">Menu</a></li>
        <div class="border"></div>
        <li><a href="#">Truck Tracker</a></li>
        <div class="border"></div>
        <li><a href="#">Our Story</a></li>
        <div class="border"></div>
        <li><a  href="#">The Truck</a></li>
        <div class="border"></div>
        <li><a href="#">Events</a></li>
        <div class="border"></div>
      </ul>
    </nav>
  </aside>
  <aside class="left">
    <a id="logo" href="#">Rossano's</a>
  </aside>

  <!-- phone icon -->
  <a href="tel:+19542242846"><i id="phone-icon" class="material-icons">
  phone_enabled
  </i></a>


  <nav class="header">
    <ul class="header">
      <li class="top-left"><a href="#">Truck Tracker</a></li>
      <li class="top-right"><a href="#">Order Online</a></li>
      <li class="b1"><a href="#">Our Story</a></li>
      <li class="b2"><a  href="#">The Truck</a></li>
      <li class="b3"><a href="#">Menu</a></li>
      <li class="b4"><a href="#">Events</a></li>
    </ul>
  </nav>
  <aside class="right">
    <p class="phone"><a href="tel:+19542242846">{954} 224-2846</a></p>
    <p class="address">Delray Beach, FL</p>
  </aside>
</header>

<div class="benvenuto">
  <p class="benvenutto">Benvenuto</p>
</div>

<section>
  <aside class="right">
    <%= image_tag 'truck9-16.jpg', class: 'truck-pic' %>
    <div class="bottom">
      <li class="one"><%= image_tag("pizza7.jpg")%></li>
      <li class="two"><%= image_tag("pizza6.jpg")%></li>
      <li class="three"><%= image_tag("pizza5.jpg")%></li>
    </div>
  </aside>

  <article class="left">
    <h1 class="making-pizza">Rossano's is the best pizza truck</h1>

    <h2 class="first">Ingredients</h2>
    <p class="first-p">Ingredients are everything to us. We handcraft our pizza sauces, salad
      dressings and signature dough daily using only the finest natural, unrefined
      ingredients. We allow our dough to rest at least a day, then hand toss it
      to ensure a delicious, golden crust. We also offer delicious, crispy,
      gluten-free crust. Our gourmet pizzas, salads and sandwiches are made when
      you order and topped with locally-grown and organic herbs and vegetables*,
      artisan meats and cheeses, and imported extra virgin olive oil.
    </p>
    <h2 class="seconde">Preparation</h2>
    <p class="seconde-p">
      Most Neapolitan pizza recipes call for placing tomatoes right onto the
      dough. The San Marzano variety of tomato is a type of Italian tomato that
      is most often used on Neapolitan pizza. You can find canned San Marzano
      tomatoes in many grocery stores in the United States these days.

      But recently, Alex and I discovered an even better trick for making a tomato
      sauce that was closer to what we remember from our Neapolitan pizza. Using
      fire-roasted tomatoes! They have a flavor that’s extremely sweet right out of
      the can. This Easy Pizza Sauce uses just 5 ingredients to make a flavor-popping
      pizza sauce that reminds us of the best pizza in Naples Italy.
    </p>
  </article>
</section>

<footer>
  <div class="left">
    <h2>Hours</h2>
    <p>Monday - Thursday: 4pm - 8pm</p>
    <p>Friday: 6pm - 10pm</p>
    <p>Sunday: 11am - 4pm</p>
  </div>

  <div class="center">
    <h2>Follow Us</h2>
    <ul>
      <!-- facebook and instagram logos link -->
      <li class="insta"><a class="fa fa-instagram" href="https://www.instagram.com/mi_cornicello/" target="_blank"></a></li>
      <li class="face"><a class="fa fa-facebook" href="https://www.facebook.com/micornicello" target="_blank"></a></li>
    </ul>
  </div>

  <div class="right">
    <h2>Get In Touch</h2>
    <p>Rossano's Pizza Truck</p>
    <p class="phone"><a href="tel:+19542242846">{954} 224-2846</a></p>
    <p class="address">Delray Beach, FL</p>
    <p class="location"><%= link_to 'Truck Location', class: "location" %></p>
  </div>

  <div class="bottom">

    <p class="left">&#169;DesignCopyright 2020 Rossano's Pizza</p>

    <%= link_to "Alex Visconde", "https://www.alexvisconde.com", target: "_black", class: "footer" %><p class="right">Site disign by</p>
  </div>


</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width >
    <title>MiCornicello</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVvMcEDDYQz2QU347ASQ1cSLlN81iLDn4&libraries=places&callback=initMaps" asyne defer >
    </script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <aside class="asideNavbar">
        <i id="navbar" class="material-icons">dehaze</i>
        <nav class="navbar">
          <!-- logo in mobel navbar -->
          <div id="logo">
            <%= link_to "Rossano's", root_path %>
          </div>

          <ul class="navbar">
            <li><%= link_to "Order Online", orderonline_index_path %></li>
            <div class="border"></div>
            <li><%= link_to "Menu", menu_index_path %></li>
            <div class="border"></div>
            <li><%= link_to "Track Location", truck_index_path %></li>
            <div class="border"></div>
            <li><%= link_to "The Truck", thetruck_index_path %></li>
            <div class="border"></div>
            <li><%= link_to "Events", events_path %></li>
            <div class="border"></div>
          </ul>
        </nav>
      </aside>

      <aside class="left">
        <%= link_to "Rossanos's", root_path %>
      </aside>

      <!-- phone icon -->
      <a href="tel:+19542242846"><i id="phone-icon" class="material-icons">
      phone_enabled
      </i></a>

      <nav class="header">
        <ul class="header">
          <li class="top-left"><%= link_to "Order Online", orderonline_index_path %></li>
          <li class="top-right"><%= link_to "Truck Location", truck_index_path %></li>
          <li class="b2"><%= link_to "The Truck", thetruck_index_path %></li>
          <li class="b3"><%= link_to "Menu", menu_index_path %></li>
          <li class="b4"><%= link_to "Events", events_path %></li>

        </ul>
      </nav>
      <aside class="right">
        <p class="phone"><a href="tel:+19542242846">(954) 224-2846</a></p>
        <p class="address">Delray Beach, FL</p>
      </aside>
    </header>

    <%= yield %>

    <!-- flash messages -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <footer>
      <div class="left">
        <h2>Hours</h2>
        <p>Monday - Thursday: 4pm - 8pm</p>
        <p>Friday: 6pm - 10pm</p>
        <p>Sunday: 11am - 4pm</p>
      </div>

      <div class="center">
        <h2>Follow Us</h2>
        <ul>
          <!-- facebook and instagram logos link -->
          <li class="insta"><a class="fa fa-instagram" href="https://www.instagram.com/mi_cornicello/" target="_blank"></a></li>
          <li class="face"><a class="fa fa-facebook" href="https://www.facebook.com/micornicello" target="_blank"></a></li>
        </ul>
      </div>

      <div class="right">
        <h2>Get In Touch</h2>
        <p>Rossano's Pizza Truck</p>
        <p class="phone"><a href="tel:+19542242846">(954) 224-2846</a></p>
        <p class="address">Delray Beach, FL</p>
        <p class="location"><%= link_to 'Truck Location', class: "location" %></p>
      </div>

      <div class="bottom">

        <p class="left">&#169;DesignCopyright 2020 Rossano's Pizza</p>

        <%= link_to "Alex Visconde", "https://www.alexvisconde.com", target: "_black", class: "footer" %><p class="right">Site disign by</p>
      </div>

    </footer>
  </body>
</html>

app/views/menu/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Menu</p>
</div>
<h1>Coming Soon!</h1>

app/views/orderonline/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Order Online</p>
</div>

<h1>Coming Soon!</h1>

app/views/thetruck/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">The Truck</p>
</div>

<h1>Coming Soon!</h1>

app/views/truck/index.html.erb
<div class="benvenuto">
  <p class="benvenutto">Truck Location</p>
</div>

<section id="google-map">
  <% if (current_user) %>
    <input id="autocomplite" type="text" placeholder="Search..." value="">
    <button id="button-truck" type="button" name="button">Clean Search</button>
  <% end %>

  <address id="createdAddress">
  </address>

  <div id="map"></div>
</section>

app/views/users/index.html.erb
<%= current_user.email %>

<% @users.each do |u| %>
<%= u.email %>
<% end %>